; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool on Mon Apr 09 2018 16:57:18 GMT+0100 (GMT Daylight Time)
M561 ; clear any bed transform
; Probe the bed at 4 points
G30 P0 X15 Y20 H15 Z-99999
G30 P1 X15 Y195 H15 Z-99999
G30 P2 X215 Y195 H15 Z-99999
G30 P3 X215 Y20 H15 Z-99999 
G30 P4 X92 Y90 H15 Z-99999 s
G1 X92 Y90 
G30 F300
;G29 S1;
